spring.application.name=bci-security-user-service

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Info Endpoint Configuration
info.app.name=${spring.application.name}
info.app.description=BCI Security User Service
info.app.version=0.0.1-SNAPSHOT
info.java.version=11
info.spring-boot.version=2.5.14

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test-bci-user-serv-db
spring.datasource.password=t3st-bci-4lm0st
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# Enable/disable direct DB integration tests (default false). Set to true to run integration tests that hit the DB
app.env.enable-integration-test=true
